// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	calculator "github.com/ZetoOfficial/aa-crystals-calc-bot/internal/calculator"
	parser "github.com/ZetoOfficial/aa-crystals-calc-bot/internal/parser"
	gomock "go.uber.org/mock/gomock"
)

// MockRatesProvider is a mock of RatesProvider interface.
type MockRatesProvider struct {
	ctrl     *gomock.Controller
	recorder *MockRatesProviderMockRecorder
	isgomock struct{}
}

// MockRatesProviderMockRecorder is the mock recorder for MockRatesProvider.
type MockRatesProviderMockRecorder struct {
	mock *MockRatesProvider
}

// NewMockRatesProvider creates a new mock instance.
func NewMockRatesProvider(ctrl *gomock.Controller) *MockRatesProvider {
	mock := &MockRatesProvider{ctrl: ctrl}
	mock.recorder = &MockRatesProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRatesProvider) EXPECT() *MockRatesProviderMockRecorder {
	return m.recorder
}

// Rates mocks base method.
func (m *MockRatesProvider) Rates(ctx context.Context) (calculator.Rates, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rates", ctx)
	ret0, _ := ret[0].(calculator.Rates)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Rates indicates an expected call of Rates.
func (mr *MockRatesProviderMockRecorder) Rates(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rates", reflect.TypeOf((*MockRatesProvider)(nil).Rates), ctx)
}

// MockParser is a mock of Parser interface.
type MockParser struct {
	ctrl     *gomock.Controller
	recorder *MockParserMockRecorder
	isgomock struct{}
}

// MockParserMockRecorder is the mock recorder for MockParser.
type MockParserMockRecorder struct {
	mock *MockParser
}

// NewMockParser creates a new mock instance.
func NewMockParser(ctrl *gomock.Controller) *MockParser {
	mock := &MockParser{ctrl: ctrl}
	mock.recorder = &MockParserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockParser) EXPECT() *MockParserMockRecorder {
	return m.recorder
}

// Parse mocks base method.
func (m *MockParser) Parse(input string) (parser.Command, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Parse", input)
	ret0, _ := ret[0].(parser.Command)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Parse indicates an expected call of Parse.
func (mr *MockParserMockRecorder) Parse(input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Parse", reflect.TypeOf((*MockParser)(nil).Parse), input)
}

// MockCalculator is a mock of Calculator interface.
type MockCalculator struct {
	ctrl     *gomock.Controller
	recorder *MockCalculatorMockRecorder
	isgomock struct{}
}

// MockCalculatorMockRecorder is the mock recorder for MockCalculator.
type MockCalculatorMockRecorder struct {
	mock *MockCalculator
}

// NewMockCalculator creates a new mock instance.
func NewMockCalculator(ctrl *gomock.Controller) *MockCalculator {
	mock := &MockCalculator{ctrl: ctrl}
	mock.recorder = &MockCalculatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCalculator) EXPECT() *MockCalculatorMockRecorder {
	return m.recorder
}

// Calculate mocks base method.
func (m *MockCalculator) Calculate(ctx context.Context, shk int, rates calculator.Rates) (calculator.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Calculate", ctx, shk, rates)
	ret0, _ := ret[0].(calculator.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Calculate indicates an expected call of Calculate.
func (mr *MockCalculatorMockRecorder) Calculate(ctx, shk, rates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Calculate", reflect.TypeOf((*MockCalculator)(nil).Calculate), ctx, shk, rates)
}

// MockFormatter is a mock of Formatter interface.
type MockFormatter struct {
	ctrl     *gomock.Controller
	recorder *MockFormatterMockRecorder
	isgomock struct{}
}

// MockFormatterMockRecorder is the mock recorder for MockFormatter.
type MockFormatterMockRecorder struct {
	mock *MockFormatter
}

// NewMockFormatter creates a new mock instance.
func NewMockFormatter(ctrl *gomock.Controller) *MockFormatter {
	mock := &MockFormatter{ctrl: ctrl}
	mock.recorder = &MockFormatterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFormatter) EXPECT() *MockFormatterMockRecorder {
	return m.recorder
}

// Result mocks base method.
func (m *MockFormatter) Result(r calculator.Result) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Result", r)
	ret0, _ := ret[0].(string)
	return ret0
}

// Result indicates an expected call of Result.
func (mr *MockFormatterMockRecorder) Result(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Result", reflect.TypeOf((*MockFormatter)(nil).Result), r)
}
